### ISSUE TITLE
The research doesn't look like what is in the UI on Figma

### ISSUE THREAD

**Issue by prezine** [Farmsby/event#1]
Web View:
<img width="1109" alt="Screenshot 2021-03-17 at 09 56 02" src="https://user-images.githubusercontent.com/20226789/111440801-fe3e9580-8706-11eb-883b-01c65ba85bb3.png">

UI Figma:
<img width="895" alt="Screenshot 2021-03-17 at 09 57 27" src="https://user-images.githubusercontent.com/20226789/111441015-304ff780-8707-11eb-9a50-64d560a4192a.png">

**Comment by ed3t** [comment]
Fixed!
